baseURL = "https://yolandapan02.github.io/"
languageCode = "en-us"
title = "Xinyue 'Yolanda' Pan"
theme = "PaperMod"

[params]
defaultTheme = "auto"

[params.profileMode]
enabled = true
title = "Hi there 👋"
subtitle = "Welcome to my website"
imageUrl = "/static/profile.jpg"
imageWidth = 200
imageHeight = 200

socialIcons = [
    { name = "github", url = "https://github.com/xpan4869" },
    { name = "linkedin", url = "https://www.linkedin.com/in/xinyue-pan-02/" }
]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "GitHub"
url = "https://github.com/xpan4869"
weight = 3